### ISSUE TITLE
turn off equivocation checking during initial sync

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/tlbc-monitor#11]
At the moment we use the height of the block to check for equivocation. This means that during the initial sync phase there cannot be any equivocation happining. That also means we don't have to check for equivocation, which will speed up things (since we do run a query for each block imported).

**Comment by jannikluhn** [comment]
Closing this as sync time seems to be not much of an issue anymore as we've got the `--sync-from` option by now.
