### ISSUE TITLE
block_fetcher.report_callbacks is not being called for the first block

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/tlbc-monitor#12]
The first block is being inserted with https://github.com/trustlines-network/tlbc-monitor/blob/cfaf8bdbe0699f5d3f784f9904e68b9c642a8d3a/monitor/block_fetcher.py#L60-L63

This misses to call the same callbacks like for every other block.

**Comment by jannikluhn** [comment]
That's fine as we'll never need to report the genesis block. Even if we sync from a later block, I don't think this would be a bug as the first block is arbitrary and if the user cares specifically about it, they should just sync with the one before that.

I think the reason we special-cased it is that the missed slot reporter will check for slots between a block and its parent, but the genesis block doesn't have a parent.

**Comment by schmir** [comment]
These arguments are not very convincing to me.
I understand that we can live with the current behaviour. Though I still consider it a bug. We do have a special case here to replicate that behaviour:

https://github.com/trustlines-network/tlbc-monitor/blob/fad91e9196fe636b30b2811b23c5b7886bb661a8/monitor/block_fetcher.py#L47-L57

If the missed slot reporter can't handle that case, it should have been handled there, not here. I'd rather do think the current behaviour has been created 'accidentally'.
