### ISSUE TITLE
object serialization compatibility check 

### ISSUE THREAD

**Issue by schmir** [trustlines-protocol/tlbc-monitor#14]
We currently do have the following code:
```
        app_state = self.db.load_pickled("appstate") or self._initialize_app_state()
        if not isinstance(app_state, AppStateV1):
            raise RuntimeError("app_state has unexpected format")
```
The problem is, if we ever store different data in an `AppStateV2` object, older version will not be able to load the pickled state, because they do not have that class.

Ideally we should also not use pickle at all because it's insecure.

**Comment by berndbohmeier** [comment]
This should with #49 at least get a good error message.

**Comment by andfletcher** [comment]
Closing this issue since this is not relevant anymore.
