### ISSUE TITLE
Cache current validator set

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/tlbc-monitor#29]
Involve a second person to discuss on how to do this.
Don't store this cache in the state.

**Comment by jannikluhn** [comment]
Draft: https://gist.github.com/jannikluhn/1c0d79c118a744e9dfa3b21b976fd6a8

**Comment by cducrest** [comment]
done as of https://github.com/trustlines-protocol/tlbc-monitor/pull/30
