### ISSUE TITLE
Monitor uses step instead of height to determine validator set

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/tlbc-monitor#32]
The validator set is determined by the block height. Only choosing the primary from the validator set is done by step. Currently, we use the step for both which effectively means we only ever use the last validator set as step is usually much larger than height.

This needs fixes at the following sites:

- https://github.com/trustlines-protocol/tlbc-monitor/blob/master/monitor/validators.py#L36 (note that this will become obsolete once #30 is merged)
- https://github.com/trustlines-protocol/tlbc-monitor/blob/master/monitor/skip_reporter.py#L65
- https://github.com/trustlines-protocol/tlbc-monitor/blob/master/monitor/offline_reporter.py#L91

**Comment by cducrest** [comment]
done as of https://github.com/trustlines-protocol/tlbc-monitor/pull/30
