### ISSUE TITLE
Fix sync message

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/tlbc-monitor#35]
The sync percentage message does not make sense anymore, as it always shows the percentage from genesis, where you know can start a sync also from later. We should fix that it actually shows the percentage of the current catch up progress. 
For example if it starts a sync at number 50 and latest is number 100 it should not start with 50% sync but with 0%.

**Comment by jannikluhn** [comment]
There's also the in practice irrelevant but in testing possible case of a zero division error: https://github.com/trustlines-protocol/tlbc-monitor/blob/master/monitor/block_fetcher.py#L259-L262

@weilbith encountered this

**Comment by berndbohmeier** [comment]
Done in #46
