### ISSUE TITLE
Write docker compose file

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-protocol/tlbc-monitor#38]
The docker compose file should

- run validator nodes
- run monitor and connect to one of the validators

c.f. https://github.com/trustlines-protocol/end2end

**Comment by weilbith** [comment]
This is done, but waits for the PR #42  to be merged.

**Comment by weilbith** [comment]
Warning:
The monitor does not support validator set contracts yet. So this service fails to start at the moment.
