### ISSUE TITLE
Manually e2e test the documented way of reporting a validator

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/tlbc-monitor#59]

**Comment by weilbith** [comment]
I've already tested it and wrote the documentation by that.
The question is, if anyone else in the team can setup a chain with an equivocating validator to test it independently.

**Comment by weilbith** [comment]
The team decided to trust me. But I have to write a new wiki page describing how to force an equivocation locally for test purpose.

**Comment by weilbith** [comment]
[Page](https://github.com/trustlines-network/project/wiki/Test-Equivocation) has been added.
