### ISSUE TITLE
Wait until deploy blocknumber

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/tlbc-monitor#83]
We saw the issue that the monitor does not wait until the validator contract it is using is deployed. 
We should have a similar mechanism as the bridge does to ensure we are in a good enough synced state to start the monitor.

**Comment by schmir-at-bb** [comment]
The above linked PR waits for the node to be fully synchronized. While it might be possible to start monitoring while warp-mode is still syncing the gap (at least in some cases), I haven't implemented it.

**Comment by berndbohmeier** [comment]
Close this for now, as this is good enough for now.
